### ISSUE TITLE
"simpleKinect is damaged and cannot be opened, please move it to the Trash"

### ISSUE THREAD

**Issue by thegladscientist** [jpbellona/simpleKinect#1]
I get this error when trying to open the simpleKinect app. I'm running OS X 10.9.2

**Comment by jpbellona** [comment]
Don't know why this error would happen. The code is zipped up by github.  hmmmm... In any case, I uploaded the working version for OSX 10.9.  The previous application only worked on 10.8 and below.

Pushed it up this morning.
https://github.com/jpbellona/simpleKinect

Best,
Jon
On Tuesday, April 8, 2014 12:57 AM, sabio-designs notifications@github.com wrote:

I get this error when trying to open the simpleKinect app. I'm running OS X 10.9.2

**Comment by jpbellona** [comment]
I later learned that this issue is related to Mac OSX handling of "3rd party" apps.  You need to go into System Preferences > Security & Privacy and make sure under "Allow apps downloaded from:", check "Anywhere".

![screen shot 2016-12-08 at 8 13 24 am](https://cloud.githubusercontent.com/assets/379410/21011215/46becb02-bd1e-11e6-8178-6b3a4835cd3e.png)
